version: "3.9"

services:
  ydb-local:
    image: ydbplatform/local-ydb:latest
    container_name: ydb-local
    hostname: localhost
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "2135:2135"   # GRPC TLS
      - "2136:2136"   # GRPC (API)
      - "8765:8765"   # Monitoring
      - "9092:9092"   # Kafka Proxy
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_KAFKA_PROXY_PORT: 9092
    volumes:
      - ./ydb_certs:/ydb_certs
      - ./ydb_data:/ydb_data

  prisma-local:
    image: node:20-alpine
    container_name: prisma-local
    hostname: prisma-local
    restart: unless-stopped
    depends_on:
      - ydb-local
    working_dir: /app
    volumes:
      - ./prisma:/app
    ports:
      - "5555:5555"   # Prisma Studio
      - "2136:2136"   # Проброс gRPC API YDB (для адаптера)
      - "2135:2135"   # Если потребуется TLS
    environment:
      # Адрес подключения к YDB
      YDB_ENDPOINT: grpc://ydb-local:2136
      YDB_DATABASE: /local
      # Опционально для Prisma
      NODE_ENV: development
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma studio --port 5555"
