services:
  ydb:
    image: ydbplatform/local-ydb:latest
    container_name: ydb-playground
    hostname: ydb
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - '2135:2135'   # GRPC TLS
      - '2136:2136'   # GRPC (API)
      - '8765:8765'   # Monitoring UI
      - '9092:9092'   # Kafka Proxy
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_KAFKA_PROXY_PORT: 9092
    volumes:
      - ./ydb_certs:/ydb_certs
      - ./ydb_data:/ydb_data

  playground-runner:
    image: node:20
    container_name: ydb-playground-runner
    hostname: playground
    depends_on:
      - ydb
    working_dir: /workspace
    volumes:
      - ../..:/workspace
    environment:
      YDB_ENDPOINT: grpc://ydb:2136
      YDB_DATABASE: /local
      DATABASE_URL: postgresql://adapter-ydb:password@localhost:5432/placeholder
      NODE_ENV: development
    command: >
      bash -c "
        npm install &&
        npx prisma generate --no-hints &&
        npx --yes --package typescript tsc &&
        node dist/playground/main.js
      "
